# notification options
notifications: 
  email:
    recipients:
      - fabian@acciente.com

# language
language: java

# language options
jdk:
  - oraclejdk7
  - oraclejdk8

# environment variables
env:
  - DB=sqlite
###  - DB=postgresql
###  - DB=mysql

# services
services:
  - sqlite3
###  - postgresql
###  - mysql

###addons:
###  postgresql: "9.3"

#-------------
# build steps
#-------------

### before_install:

install:
  - git clone https://github.com/acciente/oacc-db.git oacc-db
  - cd oacc-db
  - if git show-ref --verify --quiet refs/heads/$TRAVIS_BRANCH; then git checkout $TRAVIS_BRANCH; fi
  - cd ..

before_script:
  - sh -c "if [ '$DB' = 'sqlite' ]; then sqlite3 oacc '.read ./oacc-db/SQLite_3_8/create_tables.sql'; fi"
###  - sh -c "if [ '$DB' = 'postgresql' ]; then psql -c 'DROP DATABASE IF EXISTS mydb;' -U postgres; fi"
###  - sh -c "if [ '$DB' = 'mysql' ];      then mysql -e 'create database IF NOT EXISTS mydb;'; fi"

script:
  - mvn test -Dmaven.test.skip=false -Dtest=com.acciente.oacc.TestAll -Ddbconfig=dbconfig_sqlite.properties

### after_success:

### after_failure:

### before_deploy:

### deploy:

### after_deploy:
